file(
    STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/include/rtp/version.h"
    VERSION_PARTS REGEX "#define LIBRTP_VERSION_[A-Z]+[ ]+")

string(
    REGEX REPLACE ".+LIBRTP_VERSION_MAJOR[ ]+([0-9]+).*" "\\1"
    VERSION_MAJOR "${VERSION_PARTS}")

string(
    REGEX REPLACE ".+LIBRTP_VERSION_MINOR[ ]+([0-9]+).*" "\\1"
    VERSION_MINOR "${VERSION_PARTS}")

string(
    REGEX REPLACE ".+LIBRTP_VERSION_BUILD[ ]+([0-9]+).*" "\\1"
    VERSION_BUILD "${VERSION_PARTS}")

set(LIBRTP_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUILD}")
